apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor-scanner-ensemble.fullname" . }}
  labels:
    {{- include "harbor-scanner-ensemble.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "harbor-scanner-ensemble.selectorLabels" . | nindent 4 }}
